# Generated by Django 6.0.1 on 2026-01-31 02:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administradora',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_bancos/')),
            ],
        ),
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('IMOVEL', 'Imóvel'), ('AUTOMOVEL', 'Automóvel')], max_length=20)),
                ('valor_credito', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_entrada', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_parcelas', models.IntegerField()),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('RESERVADO', 'Reservado'), ('VENDIDO', 'Vendido')], default='DISPONIVEL', max_length=20)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='cartas/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('administradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartas', to='core.administradora')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
