# Generated by Django 6.0.1 on 2026-02-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carta',
            name='dia_vencimento',
            field=models.IntegerField(default=10, help_text='Dia do vencimento da parcela (ex: 10, 15, 20)'),
        ),
        migrations.AddField(
            model_name='carta',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Detalhes extras sobre a carta', null=True, verbose_name='Observações Gerais'),
        ),
        migrations.AddField(
            model_name='carta',
            name='taxa_transferencia',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor da taxa (0 para Grátis)', max_digits=10),
        ),
        migrations.AddField(
            model_name='carta',
            name='tipo_contemplacao',
            field=models.CharField(default='Sorteio', help_text='Ex: Sorteio, Lance, Livre', max_length=50),
        ),
    ]
