# Generated by Django 6.0.1 on 2026-02-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_carta_dia_vencimento_carta_observacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carta',
            name='saldo_devedor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Se não informado, não aparecerá no site.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='carta',
            name='seguro_vida',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Se não informado, não aparecerá no site.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='carta',
            name='dia_vencimento',
            field=models.IntegerField(default=10, help_text='Dia do vencimento da parcela'),
        ),
        migrations.AlterField(
            model_name='carta',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações Gerais'),
        ),
        migrations.AlterField(
            model_name='carta',
            name='tipo_contemplacao',
            field=models.CharField(default='Sorteio', help_text='Ex: Sorteio, Lance', max_length=50),
        ),
    ]
