# Generated by Django 6.0.1 on 2026-02-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_carta_saldo_devedor_carta_seguro_vida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carta',
            name='dia_vencimento',
        ),
        migrations.AddField(
            model_name='carta',
            name='vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='Próximo Vencimento / Validade'),
        ),
        migrations.AlterField(
            model_name='carta',
            name='saldo_devedor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Saldo Devedor'),
        ),
        migrations.AlterField(
            model_name='carta',
            name='seguro_vida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Seguro de Vida'),
        ),
    ]
