# Generated by Django 6.0.1 on 2026-02-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_carta_dia_vencimento_carta_vencimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carta',
            name='imagem',
        ),
        migrations.AlterField(
            model_name='carta',
            name='taxa_transferencia',
            field=models.CharField(default='Grátis', max_length=100, verbose_name='Taxa de Transferência'),
        ),
        migrations.AlterField(
            model_name='carta',
            name='vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='Próximo Vencimento'),
        ),
    ]
