# Generated by Django 6.0.1 on 2026-02-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_carta_imagem_alter_carta_taxa_transferencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.CharField(default='5547999999999', help_text='Apenas números (ex: 5547999999999)', max_length=20)),
                ('email_contato', models.EmailField(blank=True, max_length=254, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração Geral',
                'verbose_name_plural': 'Configurações Gerais',
            },
        ),
        migrations.AlterModelOptions(
            name='administradora',
            options={'verbose_name': 'Administradora', 'verbose_name_plural': 'Administradoras'},
        ),
        migrations.AlterModelOptions(
            name='carta',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Carta Contemplada', 'verbose_name_plural': 'Cartas Contempladas'},
        ),
        migrations.AlterField(
            model_name='carta',
            name='vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='Próximo Vencimento / Validade'),
        ),
    ]
