# Generated by Django 6.0.2 on 2026-02-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_configuracao_alter_administradora_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administradora',
            name='logo_url_externa',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da Logo Externa (API)'),
        ),
        migrations.AddField(
            model_name='carta',
            name='origem',
            field=models.CharField(choices=[('LOCAL', 'Capital X'), ('PARCEIRO', 'API Parceiro')], default='LOCAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='carta',
            name='taxa_transferencia',
            field=models.CharField(default='A consultar', max_length=100, verbose_name='Taxa de Transferência'),
        ),
    ]
